/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 *
 * Placeholder mainnet entry — replaced by `yarn deploy --network mainnet`.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  1: {
    SlopComputerFrontpage: {
      address: "0x94D987a8057b7795522589E36383C87356217820",
      abi: [
        {
          inputs: [
            { internalType: "address", name: "initialOwner", type: "address" },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "uint256", name: "index", type: "uint256" },
            { indexed: false, internalType: "string", name: "title", type: "string" },
            { indexed: false, internalType: "string", name: "cid", type: "string" },
          ],
          name: "EpisodeAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "uint256", name: "index", type: "uint256" },
            { indexed: false, internalType: "string", name: "title", type: "string" },
            { indexed: false, internalType: "string", name: "cid", type: "string" },
          ],
          name: "EpisodeUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: false, internalType: "bool", name: "isLive", type: "bool" },
            { indexed: false, internalType: "string", name: "title", type: "string" },
            { indexed: false, internalType: "string", name: "hlsUrl", type: "string" },
          ],
          name: "LiveStatusChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
            { indexed: true, internalType: "address", name: "newOwner", type: "address" },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          inputs: [
            { internalType: "string", name: "title", type: "string" },
            { internalType: "string", name: "date", type: "string" },
            { internalType: "string", name: "duration", type: "string" },
            { internalType: "string", name: "description", type: "string" },
            { internalType: "string", name: "cid", type: "string" },
          ],
          name: "addEpisode",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "episodeCount",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "uint256", name: "index", type: "uint256" }],
          name: "getEpisode",
          outputs: [
            {
              components: [
                { internalType: "string", name: "title", type: "string" },
                { internalType: "string", name: "date", type: "string" },
                { internalType: "string", name: "duration", type: "string" },
                { internalType: "string", name: "description", type: "string" },
                { internalType: "string", name: "cid", type: "string" },
              ],
              internalType: "struct SlopComputerFrontpage.Episode",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getEpisodes",
          outputs: [
            {
              components: [
                { internalType: "string", name: "title", type: "string" },
                { internalType: "string", name: "date", type: "string" },
                { internalType: "string", name: "duration", type: "string" },
                { internalType: "string", name: "description", type: "string" },
                { internalType: "string", name: "cid", type: "string" },
              ],
              internalType: "struct SlopComputerFrontpage.Episode[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "string", name: "title", type: "string" },
            { internalType: "string", name: "hlsUrl", type: "string" },
          ],
          name: "goLive",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "goOffline",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "isLive",
          outputs: [{ internalType: "bool", name: "", type: "bool" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "liveHlsUrl",
          outputs: [{ internalType: "string", name: "", type: "string" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "liveTitle",
          outputs: [{ internalType: "string", name: "", type: "string" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [{ internalType: "address", name: "", type: "address" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "uint256", name: "index", type: "uint256" },
            { internalType: "string", name: "title", type: "string" },
            { internalType: "string", name: "date", type: "string" },
            { internalType: "string", name: "duration", type: "string" },
            { internalType: "string", name: "description", type: "string" },
            { internalType: "string", name: "cid", type: "string" },
          ],
          name: "updateEpisode",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 0,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
